import { sql } from "kysely";
import type { Kysely } from "kysely";

/**
 * Generating the database types from a migrated database (New-15).
 *
 * T5 closed finding A4 by *comparing* a hand-written declaration against the
 * database and failing the build on a difference. That catches the mistake; it
 * does not prevent it, and adding a column still meant editing three places.
 * This removes the hand-maintenance: the migrations are the only place a
 * column is written down.
 *
 * It also closes a duplication nothing was checking. `OutboxState`,
 * `AccountStatus` and four more were TypeScript unions written beside a
 * `CHECK (x IN (...))` in SQL, and the two could disagree silently — the
 * database would refuse a value the compiler thought fine. The unions are now
 * read out of the constraints.
 *
 * The rendering is a pure function so it can be tested without a database; the
 * introspection is one query and needs one, which the harness already
 * provides.
 */
export interface ColumnShape {
  readonly name: string;
  readonly dataType: string;
  readonly nullable: boolean;
  /** From a `CHECK (x IN (…))`, when the column has one. */
  readonly enumValues?: readonly string[];
  /** From `COMMENT ON COLUMN`, so the reason lives with the migration. */
  readonly comment?: string;
}

export interface TableShape {
  readonly name: string;
  readonly comment?: string;
  readonly columns: readonly ColumnShape[];
}

/**
 * How a PostgreSQL type reaches TypeScript.
 *
 * **Unknown types throw.** A default of `unknown` would let a column with a
 * type nobody considered slip into the model as something the compiler cannot
 * check, which is the failure this whole file exists to prevent.
 */
const TYPES: Readonly<Record<string, string>> = {
  uuid: "string",
  text: "string",
  boolean: "boolean",
  integer: "number",
  // `pg` returns int8 as a string, because it does not fit a JavaScript
  // number. That is also why money is bigint minor units in the first place.
  bigint: "string",
  "timestamp with time zone": "Date",
  jsonb: "unknown",
};

export class UnmappedColumnTypeError extends Error {
  readonly code = "persistence.codegen.unmapped_type";

  constructor(table: string, column: string, dataType: string) {
    super(
      `${table}.${column} is "${dataType}", which has no TypeScript mapping. Add one to TYPES in codegen.ts — defaulting to \`unknown\` would hide the column from the compiler.`,
    );
    this.name = "UnmappedColumnTypeError";
  }
}

/** `effect_outbox` → `EffectOutboxTable`. */
function interfaceName(table: string): string {
  return `${table.split("_").map(pascal).join("")}Table`;
}

/** `outbox.state` with an enum → `OutboxState`, near enough to what was there. */
function unionName(table: string, column: string): string {
  return `${table.split("_").map(pascal).join("")}${column.split("_").map(pascal).join("")}`;
}

function pascal(part: string): string {
  const first = part.charAt(0);
  return first === "" ? part : first.toUpperCase() + part.slice(1);
}

function docComment(text: string | undefined, indent: string): string {
  if (text === undefined || text === "") {
    return "";
  }
  return `${indent}/** ${text} */\n`;
}

/**
 * Render the whole module.
 *
 * Pure, and takes the shapes rather than a connection, so the output can be
 * asserted against a fixture without starting PostgreSQL.
 */
export function renderSchemaModule(tables: readonly TableShape[]): string {
  const lines: string[] = [
    "// Generated by `pnpm db:types` from a freshly migrated database.",
    "// Do not edit: add a column in a migration and regenerate (New-15).",
    "//",
    "// Column comments come from `COMMENT ON` in the migrations, so the reason a",
    "// column exists is written once, where a DBA also sees it. Unions come from",
    "// `CHECK (x IN (…))`, so the type and the constraint cannot disagree.",
    "",
  ];

  for (const table of tables) {
    for (const column of table.columns) {
      if (column.enumValues === undefined) {
        continue;
      }
      lines.push(
        `export type ${unionName(table.name, column.name)} =`,
        `  | ${column.enumValues.map((value) => `"${value}"`).join("\n  | ")};`,
        "",
      );
    }
  }

  for (const table of tables) {
    const tableComment = docComment(table.comment, "").trimEnd();
    if (tableComment !== "") {
      lines.push(tableComment);
    }
    lines.push(`export interface ${interfaceName(table.name)} {`);
    for (const column of table.columns) {
      const mapped =
        column.enumValues === undefined
          ? TYPES[column.dataType]
          : unionName(table.name, column.name);
      if (mapped === undefined) {
        throw new UnmappedColumnTypeError(
          table.name,
          column.name,
          column.dataType,
        );
      }
      const comment = docComment(column.comment, "  ");
      if (comment !== "") {
        lines.push(comment.trimEnd());
      }
      // `unknown` already admits null, so `unknown | null` is a redundancy —
      // and one the lint rules refuse, in generated output as in any other.
      const nullable = column.nullable && mapped !== "unknown";
      lines.push(`  ${column.name}: ${mapped}${nullable ? " | null" : ""};`);
    }
    lines.push("}", "");
  }

  lines.push("export interface Database {");
  for (const table of tables) {
    lines.push(`  ${table.name}: ${interfaceName(table.name)};`);
  }
  lines.push("}", "");

  lines.push(
    "/**",
    " * Every column, as the migrated database has it.",
    " *",
    " * Compared against a live database by `assertSchemaMatches` (finding A4).",
    " * Generated from the same introspection as the types above, so the two",
    " * cannot disagree with each other -- only with a database that has drifted.",
    " */",
    "export const DECLARED_SCHEMA: Readonly<Record<string, readonly string[]>> = {",
  );
  for (const table of tables) {
    lines.push(`  ${table.name}: [`);
    for (const column of table.columns) {
      lines.push(`    "${column.name}",`);
    }
    lines.push("  ],");
  }
  lines.push("};", "");

  return lines.join("\n");
}

/** `x = ANY (ARRAY['a'::text, 'b'::text])` → `["a", "b"]`, or nothing. */
export function parseEnumCheck(
  definition: string,
  column: string,
): readonly string[] | undefined {
  const pattern = new RegExp(
    `\\(?${column}\\)?(?:::text)?\\s*=\\s*ANY\\s*\\(\\s*\\(?ARRAY\\[(?<values>[^\\]]+)\\]`,
  );
  const match = pattern.exec(definition);
  const values = match?.groups?.["values"];
  if (values === undefined) {
    return undefined;
  }
  const parsed = [...values.matchAll(/'([^']*)'/g)].flatMap((entry) =>
    entry[1] === undefined ? [] : [entry[1]],
  );
  return parsed.length === 0 ? undefined : parsed;
}

interface ColumnRow {
  table_name: string;
  column_name: string;
  data_type: string;
  is_nullable: string;
  ordinal_position: number;
  column_comment: string | null;
  table_comment: string | null;
}

interface CheckRow {
  table_name: string;
  definition: string;
}

/** Read the shapes out of a migrated database. */
export async function introspectForCodegen<T>(
  // Generic over the schema: this reads `information_schema`, so it works
  // against a database whose types it is about to generate — including the
  // first run, when there are none.
  db: Kysely<T>,
): Promise<readonly TableShape[]> {
  const columns = await sql<ColumnRow>`
    SELECT c.table_name,
           c.column_name,
           c.data_type,
           c.is_nullable,
           c.ordinal_position,
           col_description(fc.oid, c.ordinal_position) AS column_comment,
           obj_description(fc.oid)                     AS table_comment
    FROM information_schema.columns c
    JOIN pg_class fc ON fc.relname = c.table_name
    JOIN pg_namespace n ON n.oid = fc.relnamespace AND n.nspname = 'public'
    WHERE c.table_schema = 'public'
    ORDER BY c.table_name, c.ordinal_position
  `.execute(db);

  const checks = await sql<CheckRow>`
    SELECT conrelid::regclass::text AS table_name,
           pg_get_constraintdef(oid) AS definition
    FROM pg_constraint
    WHERE contype = 'c' AND connamespace = 'public'::regnamespace
  `.execute(db);

  const byTable = new Map<string, ColumnShape[]>();
  const comments = new Map<string, string>();

  for (const row of columns.rows) {
    const checksFor = checks.rows.filter(
      (check) => check.table_name === row.table_name,
    );
    const enumValues = checksFor
      .map((check) => parseEnumCheck(check.definition, row.column_name))
      .find((values) => values !== undefined);

    const existing = byTable.get(row.table_name) ?? [];
    existing.push({
      name: row.column_name,
      dataType: row.data_type,
      nullable: row.is_nullable === "YES",
      ...(enumValues === undefined ? {} : { enumValues }),
      ...(row.column_comment === null ? {} : { comment: row.column_comment }),
    });
    byTable.set(row.table_name, existing);
    if (row.table_comment !== null) {
      comments.set(row.table_name, row.table_comment);
    }
  }

  return [...byTable.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, tableColumns]) => {
      const comment = comments.get(name);
      return {
        name,
        ...(comment === undefined ? {} : { comment }),
        columns: tableColumns,
      };
    });
}
