/**
 * Database types, mirroring the migrated schema.
 *
 * Regenerated by `pnpm db:types` from a freshly migrated database and
 * committed; CI regenerates and fails on a diff (T5). A column that migrations
 * did not create cannot be referenced — it is a type error, which is finding
 * A4 made unrepresentable rather than merely discouraged.
 */
export interface SchemaMigrationTable {
  id: string;
  /** Written from the injected clock, never from `now()`. */
  applied_at: Date;
  irreversible_reason: string | null;
}

export interface TenantTable {
  id: string;
  slug: string;
  name: string;
  created_at: Date;
}

export interface ApiClientTable {
  id: string;
  tenant_id: string;
  client_id: string;
  secret_hash: string;
  name: string;
  disabled_at: Date | null;
  created_at: Date;
}

export interface ApiClientScopeTable {
  id: string;
  api_client_id: string;
  scope: string;
  granted_at: Date;
  granted_by: string;
  revoked_at: Date | null;
  revoked_by: string | null;
  reason: string;
}

export interface AuditEventTable {
  id: string;
  tenant_id: string;
  occurred_at: Date;
  actor_id: string | null;
  actor_kind: string;
  action: string;
  subject_type: string;
  subject_id: string;
  detail: unknown;
}

export type OutboxState =
  "pending" | "dispatched" | "confirmed" | "failed" | "unknown";

export interface IdempotencyRecordTable {
  id: string;
  tenant_id: string;
  scope: string;
  idempotency_key: string;
  request_fingerprint: string;
  state: "in_flight" | "completed";
  result: unknown;
  created_at: Date;
  completed_at: Date | null;
}

export interface EffectOutboxTable {
  id: string;
  tenant_id: string;
  aggregate_type: string;
  aggregate_id: string;
  provider_id: string;
  operation: string;
  payload: unknown;
  state: OutboxState;
  attempts: number;
  next_attempt_at: Date | null;
  lease_until: Date | null;
  leased_by: string | null;
  provider_ref: string | null;
  last_error: string | null;
  created_at: Date;
  updated_at: Date;
}

export interface ProviderInboxTable {
  id: string;
  tenant_id: string;
  provider_id: string;
  external_event_id: string | null;
  event_type: string | null;
  provider_ref: string | null;
  signature_verified: boolean;
  payload: unknown;
  received_at: Date;
  processed_at: Date | null;
  process_error: string | null;
}

export interface CustomerTable {
  id: string;
  tenant_id: string;
  external_user_uuid: string;
  created_at: Date;
  updated_at: Date;
}

export type ProviderLinkStatus =
  "pending" | "active" | "blocked" | "offboarded" | "unknown";

export interface ProviderCustomerLinkTable {
  id: string;
  tenant_id: string;
  customer_id: string;
  provider_id: string;
  external_customer_id: string;
  status: ProviderLinkStatus;
  status_reason: string | null;
  observed_at: Date;
  created_at: Date;
}

export type AccountProduct = "current_account" | "wallet" | "savings";
export type AccountStatus =
  "pending" | "active" | "frozen" | "closed" | "unknown";

/** Note the absence of a balance. See 0005_account.sql. */
export interface AccountTable {
  id: string;
  tenant_id: string;
  customer_id: string;
  provider_id: string;
  account_reference: string;
  product: AccountProduct;
  currency: string;
  status: AccountStatus;
  status_reason: string | null;
  iban: string | null;
  account_number: string | null;
  sort_code: string | null;
  bic: string | null;
  opened_at: Date | null;
  observed_at: Date;
  created_at: Date;
}

export interface BalanceObservationTable {
  id: string;
  tenant_id: string;
  account_id: string;
  currency: string;
  /** `pg` returns BIGINT as a string, which is what `Money` wants. */
  available_minor_units: string;
  current_minor_units: string;
  source: "provider_read" | "reconciled";
  observed_at: Date;
  recorded_at: Date;
}

export type TransactionDirection = "debit" | "credit";
export type TransactionStatus =
  "pending" | "settled" | "rejected" | "reversed" | "unknown";

/** No surrogate key and no projected_at: see 0007_transaction-projection.sql. */
export interface TransactionProjectionTable {
  provider_id: string;
  transaction_reference: string;
  tenant_id: string;
  account_id: string;
  direction: TransactionDirection;
  currency: string;
  amount_minor_units: string;
  status: TransactionStatus;
  counterparty_name: string | null;
  narrative: string | null;
  occurred_at: Date;
}

export interface Database {
  transaction_projection: TransactionProjectionTable;
  balance_observation: BalanceObservationTable;
  account: AccountTable;
  customer: CustomerTable;
  provider_customer_link: ProviderCustomerLinkTable;
  idempotency_record: IdempotencyRecordTable;
  effect_outbox: EffectOutboxTable;
  provider_inbox: ProviderInboxTable;
  schema_migration: SchemaMigrationTable;
  tenant: TenantTable;
  api_client: ApiClientTable;
  api_client_scope: ApiClientScopeTable;
  audit_event: AuditEventTable;
}
