// Generated by `pnpm db:types` from a freshly migrated database.
// Do not edit: add a column in a migration and regenerate (New-15).
//
// Column comments come from `COMMENT ON` in the migrations, so the reason a
// column exists is written once, where a DBA also sees it. Unions come from
// `CHECK (x IN (…))`, so the type and the constraint cannot disagree.

export type AccountProduct = "current_account" | "wallet" | "savings";

export type AccountStatus =
  "pending" | "active" | "frozen" | "closed" | "unknown";

export type BalanceObservationSource = "provider_read" | "reconciled";

export type EffectOutboxState =
  "pending" | "dispatched" | "confirmed" | "failed" | "unknown";

export type IdempotencyRecordState = "in_flight" | "completed";

export type ProviderCustomerLinkStatus =
  "pending" | "active" | "blocked" | "offboarded" | "unknown";

export type ProviderRequestLogOutcome = "ok" | "rejected" | "unreachable";

export type TransactionProjectionDirection = "debit" | "credit";

export type TransactionProjectionStatus =
  "pending" | "settled" | "rejected" | "reversed" | "unknown";

/** classification: restricted. Derived from the provider; writable only under app.provider_sync. Holds no balance: the provider is authoritative for how much money exists. */
export interface AccountTable {
  id: string;
  tenant_id: string;
  customer_id: string;
  provider_id: string;
  account_reference: string;
  product: AccountProduct;
  currency: string;
  status: AccountStatus;
  status_reason: string | null;
  /** classification: restricted. A bank identifier for a named person. */
  iban: string | null;
  /** classification: restricted. A bank identifier for a named person. */
  account_number: string | null;
  sort_code: string | null;
  bic: string | null;
  opened_at: Date | null;
  observed_at: Date;
  created_at: Date;
}

export interface ApiClientTable {
  id: string;
  tenant_id: string;
  client_id: string;
  /** classification: secret. bcrypt; never logged, never returned. */
  secret_hash: string;
  name: string;
  disabled_at: Date | null;
  created_at: Date;
}

export interface ApiClientScopeTable {
  id: string;
  api_client_id: string;
  scope: string;
  granted_at: Date;
  granted_by: string;
  revoked_at: Date | null;
  revoked_by: string | null;
  reason: string;
}

export interface AuditEventTable {
  id: string;
  tenant_id: string;
  occurred_at: Date;
  actor_id: string | null;
  actor_kind: string;
  action: string;
  subject_type: string;
  subject_id: string;
  detail: unknown;
}

/** classification: restricted. What a provider said a balance was, and when. Append-only; the latest row is not the truth, it is the most recent evidence. */
export interface BalanceObservationTable {
  id: string;
  tenant_id: string;
  account_id: string;
  currency: string;
  /** Minor units. Never a float: an amount that has been through a double is already wrong. */
  available_minor_units: string;
  current_minor_units: string;
  source: BalanceObservationSource;
  observed_at: Date;
  recorded_at: Date;
}

/** classification: restricted. Pseudonymous identity only; no direct personal data. */
export interface CustomerTable {
  id: string;
  tenant_id: string;
  /** classification: restricted. The end user as the BFF knows them. Pseudonymous, but re-identifiable by the BFF, so it is not free of personal data. */
  external_user_uuid: string;
  created_at: Date;
  updated_at: Date;
}

export interface EffectOutboxTable {
  id: string;
  tenant_id: string;
  aggregate_type: string;
  aggregate_id: string;
  provider_id: string;
  operation: string;
  payload: unknown;
  state: EffectOutboxState;
  attempts: number;
  next_attempt_at: Date | null;
  lease_until: Date | null;
  leased_by: string | null;
  provider_ref: string | null;
  last_error: string | null;
  created_at: Date;
  updated_at: Date;
}

export interface IdempotencyRecordTable {
  id: string;
  tenant_id: string;
  scope: string;
  idempotency_key: string;
  /** A reused key with a different fingerprint is refused, not replayed. */
  request_fingerprint: string;
  state: IdempotencyRecordState;
  result: unknown;
  created_at: Date;
  completed_at: Date | null;
}

/** classification: restricted. Staff identity from the identity provider. */
export interface OperatorTable {
  id: string;
  tenant_id: string;
  issuer: string;
  /** The OIDC `sub`. Stable for the life of the account at the provider; the natural key together with the issuer. */
  subject: string;
  /** classification: restricted. Personal data. Held so an audit row names a person rather than a uuid. */
  email: string | null;
  display_name: string | null;
  disabled_at: Date | null;
  created_at: Date;
  updated_at: Date;
}

export interface OperatorRoleTable {
  id: string;
  operator_id: string;
  tenant_id: string;
  role: string;
  granted_at: Date;
  granted_by: string | null;
  revoked_at: Date | null;
  revoked_by: string | null;
  reason: string;
}

export interface OperatorSessionTable {
  id: string;
  tenant_id: string;
  operator_id: string;
  /** classification: secret. SHA-256 of the bearer token. The token itself is never stored. */
  token_hash: string;
  issued_at: Date;
  expires_at: Date;
  revoked_at: Date | null;
  last_seen_at: Date | null;
}

/** classification: restricted. Derived state: writable only under app.provider_sync, never through an API. */
export interface ProviderCustomerLinkTable {
  id: string;
  tenant_id: string;
  customer_id: string;
  provider_id: string;
  external_customer_id: string;
  status: ProviderCustomerLinkStatus;
  status_reason: string | null;
  observed_at: Date;
  created_at: Date;
}

/** classification: restricted. Holds raw provider bodies and therefore PII; inherits the strictest retention in the service. */
export interface ProviderInboxTable {
  id: string;
  tenant_id: string;
  provider_id: string;
  external_event_id: string | null;
  event_type: string | null;
  provider_ref: string | null;
  signature_verified: boolean;
  payload: unknown;
  received_at: Date;
  processed_at: Date | null;
  process_error: string | null;
}

/** classification: restricted, shortest retention in the service. Provider request and response bodies, scrubbed on write. Reads are audited. */
export interface ProviderRequestLogTable {
  id: string;
  tenant_id: string;
  provider_id: string;
  /** Method and path. Never the query string: query parameters carry account references. */
  operation: string;
  correlation_id: string | null;
  idempotency_id: string | null;
  outcome: ProviderRequestLogOutcome;
  response_status: number | null;
  /** classification: restricted. Scrubbed of named personal-data shapes on write, which is a reduction of risk and not an elimination of it. */
  request_body: string;
  /** classification: restricted. As above. */
  response_body: string;
  error_message: string | null;
  started_at: Date;
  duration_ms: number;
  retention_until: Date;
  /** classification: restricted. The account a call was about, when it was about one. Indexed so an incident can be traced from the only identifier support usually has. */
  account_reference: string | null;
}

export interface SchemaMigrationTable {
  id: string;
  applied_at: Date;
  irreversible_reason: string | null;
}

/** classification: operational. One row until a second tenant exists. */
export interface TenantTable {
  id: string;
  slug: string;
  name: string;
  created_at: Date;
}

/** classification: restricted. Derived read model with exactly one writer. Rebuildable: drop it and re-project, and the rows are identical. */
export interface TransactionProjectionTable {
  provider_id: string;
  transaction_reference: string;
  tenant_id: string;
  account_id: string;
  direction: TransactionProjectionDirection;
  currency: string;
  amount_minor_units: string;
  status: TransactionProjectionStatus;
  /** classification: restricted. Names a third party to the customer. */
  counterparty_name: string | null;
  narrative: string | null;
  occurred_at: Date;
}

export interface Database {
  account: AccountTable;
  api_client: ApiClientTable;
  api_client_scope: ApiClientScopeTable;
  audit_event: AuditEventTable;
  balance_observation: BalanceObservationTable;
  customer: CustomerTable;
  effect_outbox: EffectOutboxTable;
  idempotency_record: IdempotencyRecordTable;
  operator: OperatorTable;
  operator_role: OperatorRoleTable;
  operator_session: OperatorSessionTable;
  provider_customer_link: ProviderCustomerLinkTable;
  provider_inbox: ProviderInboxTable;
  provider_request_log: ProviderRequestLogTable;
  schema_migration: SchemaMigrationTable;
  tenant: TenantTable;
  transaction_projection: TransactionProjectionTable;
}

/**
 * Every column, as the migrated database has it.
 *
 * Compared against a live database by `assertSchemaMatches` (finding A4).
 * Generated from the same introspection as the types above, so the two
 * cannot disagree with each other -- only with a database that has drifted.
 */
export const DECLARED_SCHEMA: Readonly<Record<string, readonly string[]>> = {
  account: [
    "id",
    "tenant_id",
    "customer_id",
    "provider_id",
    "account_reference",
    "product",
    "currency",
    "status",
    "status_reason",
    "iban",
    "account_number",
    "sort_code",
    "bic",
    "opened_at",
    "observed_at",
    "created_at",
  ],
  api_client: [
    "id",
    "tenant_id",
    "client_id",
    "secret_hash",
    "name",
    "disabled_at",
    "created_at",
  ],
  api_client_scope: [
    "id",
    "api_client_id",
    "scope",
    "granted_at",
    "granted_by",
    "revoked_at",
    "revoked_by",
    "reason",
  ],
  audit_event: [
    "id",
    "tenant_id",
    "occurred_at",
    "actor_id",
    "actor_kind",
    "action",
    "subject_type",
    "subject_id",
    "detail",
  ],
  balance_observation: [
    "id",
    "tenant_id",
    "account_id",
    "currency",
    "available_minor_units",
    "current_minor_units",
    "source",
    "observed_at",
    "recorded_at",
  ],
  customer: [
    "id",
    "tenant_id",
    "external_user_uuid",
    "created_at",
    "updated_at",
  ],
  effect_outbox: [
    "id",
    "tenant_id",
    "aggregate_type",
    "aggregate_id",
    "provider_id",
    "operation",
    "payload",
    "state",
    "attempts",
    "next_attempt_at",
    "lease_until",
    "leased_by",
    "provider_ref",
    "last_error",
    "created_at",
    "updated_at",
  ],
  idempotency_record: [
    "id",
    "tenant_id",
    "scope",
    "idempotency_key",
    "request_fingerprint",
    "state",
    "result",
    "created_at",
    "completed_at",
  ],
  operator: [
    "id",
    "tenant_id",
    "issuer",
    "subject",
    "email",
    "display_name",
    "disabled_at",
    "created_at",
    "updated_at",
  ],
  operator_role: [
    "id",
    "operator_id",
    "tenant_id",
    "role",
    "granted_at",
    "granted_by",
    "revoked_at",
    "revoked_by",
    "reason",
  ],
  operator_session: [
    "id",
    "tenant_id",
    "operator_id",
    "token_hash",
    "issued_at",
    "expires_at",
    "revoked_at",
    "last_seen_at",
  ],
  provider_customer_link: [
    "id",
    "tenant_id",
    "customer_id",
    "provider_id",
    "external_customer_id",
    "status",
    "status_reason",
    "observed_at",
    "created_at",
  ],
  provider_inbox: [
    "id",
    "tenant_id",
    "provider_id",
    "external_event_id",
    "event_type",
    "provider_ref",
    "signature_verified",
    "payload",
    "received_at",
    "processed_at",
    "process_error",
  ],
  provider_request_log: [
    "id",
    "tenant_id",
    "provider_id",
    "operation",
    "correlation_id",
    "idempotency_id",
    "outcome",
    "response_status",
    "request_body",
    "response_body",
    "error_message",
    "started_at",
    "duration_ms",
    "retention_until",
    "account_reference",
  ],
  schema_migration: ["id", "applied_at", "irreversible_reason"],
  tenant: ["id", "slug", "name", "created_at"],
  transaction_projection: [
    "provider_id",
    "transaction_reference",
    "tenant_id",
    "account_id",
    "direction",
    "currency",
    "amount_minor_units",
    "status",
    "counterparty_name",
    "narrative",
    "occurred_at",
  ],
};
